name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          check_together: 'yes'
          scandir: './src'

  bats-test:
    name: BATS Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup BATS
        uses: bats-core/bats-action@2.0.0
      
      - name: Run BATS tests
        run: bats tests/test_navarch.bats

  shfmt:
    name: Shell Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      
      - name: Install shfmt
        run: go install mvdan.cc/sh/v3/cmd/shfmt@latest
      
      - name: Check shell script formatting
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          shfmt -d -ci src/navarch